worker_processes 1;
error_log /dev/null;

events {
    worker_connections 1024;
}

http {
    access_log off;

    upstream api {
        server unix:/run/uds/api1.sock;
        server unix:/run/uds/api2.sock;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
